cat $1 | grep " yearh " > T_2_green_yeah.txt
cat $1 | grep " one " > T_3_green_one.txt
cat $1 | grep " five " > T_5_green_five.txt
cat $1 | grep " zan " > T_7_green_zan.txt
cat $1 | grep " fingerheart " > T_8_green_fheart.txt
cat $1 | grep " ok " > T_9_green_ok.txt
cat $1 | grep " call " > T_10_green_call.txt
cat $1 | grep " rock " > T_11_green_rock.txt
cat $1 | grep " big_v " > T_12_green_big_v.txt
cat $1 | grep " fist " > T_13_green_fist.txt
cat $1 | grep " palm " > T_15_green_palm.txt
cat $1 | grep " thumb_down " > T_16_green_thumb_down.txt
