./build/tools/caffe time \
--model=no_bn.prototxt -iterations 3000
#--model=examples/hand_cls/mouth48/mergebn14cls.prototxt -iterations 3000
#--model=examples/hand_cls/mouth48/test14cls.prototxt -iterations 3000
#--model=examples/hand_cls/mouth48/bnTest.prototxt -iterations 3000
#--model=models/prototxt/lm87_64b_cls.prototxt -iterations 3000
#--model=/Users/momo/wkspace/caffe_space/detection/caffe/examples/hand_reg/lm87_64/test.prototxt -iterations 3000
#--model=models/prototxt/hand_gesture_reg_v3.0.prototxt -iterations 3000
#--model=models/prototxt/hand_gesture_reg_v3.0.prototxt -iterations 3000
#--model=models/prototxt/lm87small.prototxt -iterations 3000
